

export const moduleDefaults = {
  business: {
    channels: [] as string[],
    payment_methods: [] as string[],
    providers: [] as string[],
    destinations: [] as string[],
    default_vat_percent: 27,
    price_input_mode: 'gross' as 'net' | 'gross',
    order_statuses: ['Függőben', 'Feldolgozás alatt', 'Szállítva', 'Teljesítve', 'Visszautaltva'],
    order_status_colors: {
      Függőben: 'warning',
      'Feldolgozás alatt': 'info',
      Szállítva: 'primary',
      Teljesítve: 'success',
      Visszautaltva: 'danger',
    } as Record<string, 'success' | 'warning' | 'danger' | 'info' | 'primary' | 'neutral'>,
    shopify_sync_schedule: 'off' as 'off' | 'hourly' | 'every_6_hours' | 'daily',
    shopify_last_synced_at: null as string | null,
    sumup_last_synced_at: null as string | null,
    tax_regime: 'aam' as 'aam' | 'vat' | 'kata',
    income_tax_method: 'cost_ratio' as 'cost_ratio' | 'actual' | 'kata_flat',
    cost_ratio_percent: 40,
    revenue_basis: 'documented_only' as 'documented_only' | 'all_orders',
  },
  dashboard: {
    widget_order: [
      'alerts',
      'ai_cfo',
      'travel_plans',
      'primary_metrics',
      'secondary_metrics',
      'main_grid',
      'business_chart',
      'ai_briefing',
    ] as const,
    widgets: {
      monthly_advisor: true,
      weekly_report: true,
      payment_priority: true,
    },
  },
  pocket_money: {
    currencies: ['HUF', 'EUR'] as string[],
    default_currency: 'HUF' as string,

    interest_reminder_days_at_month_end: 3,
  },
  insurance: {
    reminder_days_before: 30,
    currencies: ['HUF', 'EUR'] as string[],
    default_currency: 'HUF' as string,
    payment_category_pattern: 'biztosít',
    budget_sync_default: false,
  },
  rental: {
    currencies: ['HUF', 'EUR'] as string[],
    default_currency: 'HUF' as string,
    contract_reminder_days_before: 60,
    overdue_grace_days: 0,
    budget_sync_default: false,
    income_category_pattern: 'bérlet',
  },
  budget: {
    category_groups: [] as Array<{ name: string; color: string; categories: string[] }>,
    category_colors: {} as Record<string, string>,
    clone_mode: 'all' as 'all' | 'budget_only' | 'fixed_recurring',
    missed_income_enabled: true,
    missed_income_grace_days: 0,
    default_currency: 'HUF' as 'HUF' | 'EUR' | 'USD',
  },
  debts: {
    default_strategy: 'avalanche' as const,
    default_extra_monthly: 0,
    pay_add_to_budget_default: true,
    payment_category_pattern: 'hitel|tartoz|törleszt',
    reminder_days_before: 3,
    default_interest_rate_annual: 0,
    debt_type_templates: [
      { label: 'Lakáshitel', default_interest_rate_annual: 5 },
      { label: 'Autóhitel', default_interest_rate_annual: 8 },
      { label: 'Hitelkártya', default_interest_rate_annual: 18 },
      { label: 'Személyi kölcsön', default_interest_rate_annual: 12 },
    ],
  },
  utilities: {
    clone_from_previous_month: true,
    settlement_auto_suggest: true,
    default_payer_user_id: null as number | null,
  },
  savings: {
    owners: [] as string[],
    default_owner: '',
    separate_owner: '',
    currencies: ['HUF', 'EUR', 'USD'] as string[],
    default_count_in_savings: true,
  },
  meters: {
    default_location: 'Otthon',
    units: ['kWh', 'm³', 'GJ'] as string[],
    templates: [
      { name: 'Villany', unit: 'kWh', location: 'Otthon' },
      { name: 'Víz', unit: 'm³', location: 'Otthon' },
      { name: 'Gáz', unit: 'm³', location: 'Otthon' },
    ],
    reading_reminder_day: 5,
    consumption_alert_percent: 25,
    show_annual_summary_on_dashboard: true,
    location_groups: [{ name: 'Otthon', locations: ['Otthon'] }],
  },
} as const;
